apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ERXpNREV4TXpVME1Wb1hEVE15TURFeU9URXhNelUwTVZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWc0Ckd6MFVCUnJnZjVxb0xVWk8zWDZvcXZ0WXhSZUIrUkI5SVpTVGcxSkJvZXlKb2hPTVhjeW1qY2VoTlA1R1ZWQUkKdSsrMHFrTEpCbG81eHFEY0JwTUlBMmM2cEZ6c3l0cjA2a3dEUFl1eWwrV3ZXeTZ6ZHliNlYvYjNSS2M5b2g2WApwRWw1ZkpLQnI4aHo3T3l4VWFtbFo3ODQzcElpL29OeXExMXRoOUxxcGFMRFZlZEhoVnZMRmltbkUyMTg2ZEQwCkdaN2ZRQ1FkOEVYemc0aGg2bEh5TjRTalpMTDJFVzduajNGUktCVHdzZHdZNzVCQlF1dkF2VmZhZEl2eVRPRVkKR0ZBZmR0bkZvdkUvcWRnQkFzcEN6Tkd0SVN1V1BqNy9vMG9wVUdHSlpZdzJ5dXV2Y2RyeXhMRGlKeFVVcldJVgp4VEgxbTV1WXJMTVp4QVdnTDA4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSUlNMdUZpSHpBNkpXUStpdVNxVUprU2ZoUEhUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFQd1UwRkNxTwoxYWU1cU9Jcmdzc3JRZ2tURVlVYUtRTVlBMnZIeW9rQ2hkSG1kU3hjbmdXUzhlY3hQaHkzZjg4Ky92d2VTQ0thCk9xejh5OGI5NEllcnFvLzNqNWYxWDVqODQ2OSs3cC9SazVydk1DUXhyRTJ6UXpsbjFoUHZFbThwekUwTVd0SXUKaFE5WGI3QjBNdWlsQ0tsYk03T0gvZlVURWQvbk5DOGkxdU43RXhJc1lyZkEwWXhqd3diOFlVd2lIMGFXOHBvRApQejR1dkh6VXlHK1J1ZVR3L2k2L2xyZkxXWm5kcUJDRzVwVW9KOTVJY0gwaEVuY1dEai9PQ01ZM3NtaGFnbnYvCk1YdmZwSDdpWkJhOW1uMVdCV3UyZ2p6dEFmMWUzWUJTZEVKeDk1YTZFdFJ3Y0pRbWFXS29pMjdPNm8xekthU2cKTFQvclFCWkg3U291S1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluSnFTbWhZVldSSFRYWk1lazVRWVdGcFowWTBlVGhQTWs5emNsVlZRM3BGTFVVd2NXSjVlRnBHZWpRaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMTNabW80ZHlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pT0RJell6UTBPV1F0TmpRM05pMDBPR015TFRrelpEUXRZMk14WTJOa1ltVTBNamRqSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5pX2JzNUFKZEpxcHl0YkNEbUtpNk8zbkRJcEY4WG5KYUZ0Y3NROUEzSmhMWGVlb29FOW9FT1dReHZtZGo0ekUxRlpTdUxvbjMzUWFDQkdjeURtbjlaeHc4NzNHbmxkTHVhMlFma1EwVkFTalRBM3VKR0ZVaF9LQ0FKNzRwN1JUaUdCMUlZOWJKZzRfM0hXWC1sMjdqSjFxMV9SRnhaeDdXTng4SlFScUlWYm9MS2pSZFl5alJhX0lnQUllWkZ5aWZVUHpnWHlna2FrelMxRlBFTjlRZWpDNFhOajFjZzVwOXdtZVRkWkhGY21YVy1lVXd1VHpWMEt6Zm1GR3dVQmZTSEdGb1lGOVVFbWlqR3FvVzlqQmUxRktHMXJNdlpZV010c3hRcFMxdXdiYkkxc3pYSTR6cnRyajd2QzY1RE5xLTVDdXBfTmktLXY5LUp2OXM1NFhHZHc=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 823c449d-6476-48c2-93d4-cc1ccdbe427c
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T15:25:20Z"
  name: default-token-wfj8w
  namespace: guestbook
type: kubernetes.io/service-account-token
